---
AUTHC_CONFIG:
    default_algorithm: bcrypt_sha256
    hash_algorithms:
        bcrypt_sha256: {}
        sha256_crypt:
            default_rounds: 110000
            max_rounds: 1000000
            min_rounds: 1000
            salt_size: 16

REMEMBER_ME_CONFIG:
    default_cipher_key: you need to update this using the fernet keygen

SECURITY_MANAGER_CONFIG:
    security_manager: yosai.web.WebSecurityManager
    attributes:
        realms:
            yosai.core.AccountStoreRealm: yosai_alchemystore.AlchemyAccountStore
        cache_handler: yosai_dpcache.cache.DPCacheHandler
        session_attributes_schema: {}

SESSION_CONFIG:
    session_timeout:
        absolute_timeout: 1800
        idle_timeout: 300
    session_validation:
        scheduler_enabled: false
        time_interval: 3600
