---
AUTHC_CONFIG:
    default_algorithm: bcrypt_sha256
    hash_algorithms:
        bcrypt_sha256: {}
        sha256_crypt:
            default_rounds: 110000
            max_rounds: 1000000
            min_rounds: 1000
            salt_size: 16


LOGGING_CONFIG:
    version : 1
    disable_existing_loggers : false
    formatters:
            print_format:
                format : "%(asctime)s\t(levelname)s:%(name)s\t%(message)s"
            json_format:
                # not sure whether this works -- TBD:
                class: yosai.core.logging.JSONFormatter
    handlers:
            console:
                class: logging.StreamHandler
                level: DEBUG
                stream: ext://sys.stdout
                formatter: print_format
            info_file_handler:
                class: logging.handlers.RotatingFileHandler
                level: INFO
                filename: info.log
                formatter: json_format
                maxBytes: 10485760
                backupCount: 20
                encoding: utf8
            error_file_handler:
                class: logging.handlers.RotatingFileHandler
                level: ERROR
                filename: errors.log
                formatter: json_format
                maxBytes: 10485760
                backupCount: 20
                encoding: utf8
    loggers:
            yosai_logger:
                level: INFO
                handlers: [console, info_file_handler]
                propagate: no
    root:
        level: INFO
        handlers: [console, info_file_handler, error_file_handler]


MGT_CONFIG:
    DEFAULT_CIPHER_KEY: you need to update this using the fernet keygen


SESSION_CONFIG:
    session_timeout:
        absolute_timeout: 1800
        idle_timeout: 300
    session_validation:
        scheduler_enabled: true
        time_interval: 3600
