---
AUTHC_CONFIG:
    default_algorithm: bcrypt_sha256
    hash_algorithms:
        bcrypt_sha256: {}
        sha256_crypt:
            default_rounds: 110000
            max_rounds: 1000000
            min_rounds: 1000
            salt_size: 16


MGT_CONFIG:
    DEFAULT_CIPHER_KEY: you need to update this using the fernet keygen


SESSION_CONFIG:
    session_timeout:
        absolute_timeout: 1800
        idle_timeout: 300
    session_validation:
        scheduler_enabled: true
        time_interval: 3600
