site_name: Yosai
repo_url: https://github.com/yosaiproject
#theme:  bootstrap
markdown_extensions:
  - fenced_code
  - codehilite:
        noclasses: True
        pygments_style: monokai
  - admonition:

pages:
- Home: index.md
- Documentation:
    - Authentication: authentication.md
    - Authorization: authorization.md
